spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/my-realm
          jwk-set-uri: http://localhost:8088/realms/my-realm/protocol/openid-connect/certs